/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if _MSC_VER
#pragma pack (push,4)
#endif

#ifndef VMDNATIVE_API
#define VMDNATIVE_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern VMDNATIVE_API FName VMDNATIVE_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class VMDNATIVE_API AVMDUnlitFixer : public AActor
{
public:
    DECLARE_FUNCTION(execPatchUnlitSurfaces);
    DECLARE_CLASS(AVMDUnlitFixer,AActor,0)
    NO_DEFAULT_CONSTRUCTOR(AVMDUnlitFixer)
};


class VMDNATIVE_API AVMDPathRebuilder : public AActor
{
public:
    DECLARE_FUNCTION(execEndShakedown);
    DECLARE_FUNCTION(execBeginShakedown);
    DECLARE_FUNCTION(execRedefinePaths);
    DECLARE_FUNCTION(execScoutSetup);
    DECLARE_FUNCTION(execAllowScoutToSpawn);
    DECLARE_CLASS(AVMDPathRebuilder,AActor,0)
    NO_DEFAULT_CONSTRUCTOR(AVMDPathRebuilder)
};


class VMDNATIVE_API AVMDNihilumCleaner : public AActor
{
public:
    BITFIELD bIgnoreNextShowMenu:1 GCC_PACK(4);
    class URootWindow* RootWindow GCC_PACK(4);
    DECLARE_FUNCTION(execSilenceNihilum);
    DECLARE_CLASS(AVMDNihilumCleaner,AActor,0)
    NO_DEFAULT_CONSTRUCTOR(AVMDNihilumCleaner)
};


class VMDNATIVE_API AVMDLightRebuilder : public AActor
{
public:
    DECLARE_FUNCTION(execRebuildLighting);
    DECLARE_CLASS(AVMDLightRebuilder,AActor,0)
    NO_DEFAULT_CONSTRUCTOR(AVMDLightRebuilder)
};


class VMDNATIVE_API AVMDHDSpacefix : public AActor
{
public:
    DECLARE_FUNCTION(execGetFreeHDSpace);
    DECLARE_CLASS(AVMDHDSpacefix,AActor,0)
    NO_DEFAULT_CONSTRUCTOR(AVMDHDSpacefix)
};


class VMDNATIVE_API AVMDGenericNativeFunctions : public AActor
{
public:
    DECLARE_FUNCTION(execGNativeSwap0);
    DECLARE_FUNCTION(execSwapGNative);
    DECLARE_FUNCTION(execHexDumpScript);
    DECLARE_FUNCTION(execTargetScriptsAreEqual);
    DECLARE_FUNCTION(execSwapTargetScripts);
    DECLARE_FUNCTION(execSetArrayPropertyText);
    DECLARE_FUNCTION(execGetArrayPropertyText);
    DECLARE_CLASS(AVMDGenericNativeFunctions,AActor,0)
    NO_DEFAULT_CONSTRUCTOR(AVMDGenericNativeFunctions)
};


class VMDNATIVE_API AVMDFileFinder : public AActor
{
public:
    DECLARE_FUNCTION(execGetFileLocation);
    DECLARE_FUNCTION(execCreateFolderAt);
    DECLARE_FUNCTION(execCopyFileFrom);
    DECLARE_FUNCTION(execGetLatestSaveDir);
    DECLARE_FUNCTION(execFindNextFileAt);
    DECLARE_FUNCTION(execFindFileAt);
    DECLARE_CLASS(AVMDFileFinder,AActor,0)
    NO_DEFAULT_CONSTRUCTOR(AVMDFileFinder)
};


class VMDNATIVE_API UKentiesUIFix : public UObject
{
public:
    DECLARE_FUNCTION(execApplyScaling);
    DECLARE_FUNCTION(execAssertHook);
    DECLARE_CLASS(UKentiesUIFix,UObject,0)
    NO_DEFAULT_CONSTRUCTOR(UKentiesUIFix)
};

#endif

AUTOGENERATE_FUNCTION(UKentiesUIFix,-1,execApplyScaling);
AUTOGENERATE_FUNCTION(UKentiesUIFix,-1,execAssertHook);
AUTOGENERATE_FUNCTION(AVMDUnlitFixer,-1,execPatchUnlitSurfaces);
AUTOGENERATE_FUNCTION(AVMDPathRebuilder,-1,execEndShakedown);
AUTOGENERATE_FUNCTION(AVMDPathRebuilder,-1,execBeginShakedown);
AUTOGENERATE_FUNCTION(AVMDPathRebuilder,-1,execRedefinePaths);
AUTOGENERATE_FUNCTION(AVMDPathRebuilder,-1,execScoutSetup);
AUTOGENERATE_FUNCTION(AVMDPathRebuilder,-1,execAllowScoutToSpawn);
AUTOGENERATE_FUNCTION(AVMDNihilumCleaner,-1,execSilenceNihilum);
AUTOGENERATE_FUNCTION(AVMDLightRebuilder,-1,execRebuildLighting);
AUTOGENERATE_FUNCTION(AVMDHDSpacefix,-1,execGetFreeHDSpace);
AUTOGENERATE_FUNCTION(AVMDGenericNativeFunctions,-1,execGNativeSwap0);
AUTOGENERATE_FUNCTION(AVMDGenericNativeFunctions,-1,execSwapGNative);
AUTOGENERATE_FUNCTION(AVMDGenericNativeFunctions,-1,execHexDumpScript);
AUTOGENERATE_FUNCTION(AVMDGenericNativeFunctions,-1,execTargetScriptsAreEqual);
AUTOGENERATE_FUNCTION(AVMDGenericNativeFunctions,-1,execSwapTargetScripts);
AUTOGENERATE_FUNCTION(AVMDGenericNativeFunctions,-1,execSetArrayPropertyText);
AUTOGENERATE_FUNCTION(AVMDGenericNativeFunctions,-1,execGetArrayPropertyText);
AUTOGENERATE_FUNCTION(AVMDFileFinder,-1,execGetFileLocation);
AUTOGENERATE_FUNCTION(AVMDFileFinder,-1,execCreateFolderAt);
AUTOGENERATE_FUNCTION(AVMDFileFinder,-1,execCopyFileFrom);
AUTOGENERATE_FUNCTION(AVMDFileFinder,-1,execGetLatestSaveDir);
AUTOGENERATE_FUNCTION(AVMDFileFinder,-1,execFindNextFileAt);
AUTOGENERATE_FUNCTION(AVMDFileFinder,-1,execFindFileAt);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#endif
